# Stesso elenco di core/index.html (ISSUERS). Se cambia uno, aggiorna l'altro.
import re
ISS = [(l, re.compile(p, re.I)) for l, p in [
    ('iShares', '\\bishares\\b|\\bishs\\b|^is\\.|^ish|^isiv\\b|^is\\b|^isvp\\b'),
    ('Xtrackers', '\\bxtrackers\\b|^xtr\\b|^xtr\\.|^xt\\b|^xt\\d|^x\\b|^x\\(ie\\)'),
    ('Amundi', '\\bamundi\\b|^ais\\b|^mul\\b|^muf\\b|^am\\b|^amndi\\b|^amun\\b'),
    ('Lyxor', '\\blyxor\\b'),
    ('WisdomTree', '\\bwisdomtree\\b|\\bwisdom tree\\b|^witr\\b|^wt\\b'),
    ('Invesco', '\\binvesco|^ivz\\b|^im2\\b|^imii\\b'),
    ('SPDR / State Street', '\\bspdr\\b|\\bstate street\\b'),
    ('Vanguard', '\\bvanguard\\b|^vang\\b'),
    ('VanEck', '\\bvaneck\\b'),
    ('HSBC', '\\bhsbc\\b'),
    ('BNP Paribas', '\\bbnp\\b|^bnpp'),
    ('Societe Generale', '\\bsg\\b|^sgis\\b|\\bsociete generale\\b'),
    ('JPMorgan', '\\bjpm\\b|\\bjpmorgan\\b'),
    ('L&G', '\\bl&g\\b|\\blegal ?& ?general\\b'),
    ('Franklin Templeton', '\\bfranklin\\b|^ftgf\\b'),
    ('Fidelity', '\\bfidelity\\b|^fid\\d?\\b'),
    ('PIMCO', '\\bpimco\\b'),
    ('GraniteShares', '\\bgraniteshares\\b'),
    ('Leverage Shares', '\\bleverage ?shares\\b'),
    ('Goldman Sachs', '\\bgoldman\\b'),
    ('DWS', '\\bdws\\b'),
    ('Deka', '\\bdeka\\b|^dk\\b'),
    ('UBS', '\\bubs\\b'),
    ('Fineco', '\\bfineco\\b'),
    ('CoinShares', '\\bcoinshares\\b'),
    ('21Shares', '\\b21shares\\b'),
    ('Global X', '\\bglobal ?x\\b'),
    ('Pictet', '\\bpictet\\b'),
    ('Allianz', '\\ballianz\\b'),
    ('onemarkets', '\\bonemarkets\\b'),
    ('D-X', '^d-x\\b|^d x\\b'),
    ('Ossiam', '\\bossiam\\b'),
    ('IndexIQ', '\\bindexiq\\b'),
    ('AllianceBernstein', '\\balliancebernstein\\b'),
    ('Robeco', '\\brobeco\\b'),
    ('Schroders', '\\bschrod?ers?\\b'),
    ('HANetf', '\\bhanetf\\b|^han\\b'),
    ('First Trust', '\\bfirst trust\\b'),
    ('KraneShares', '\\bkrane(shares)?\\b'),
    ('Janus Henderson', '\\bjanus henderson\\b'),
    ('Virtune', '\\bvirtune\\b'),
    ('Bitwise', '\\bbitwise\\b'),
    ('Leonteq', '\\bleon[ .]sec'),
    ('NXTassets', '\\bnxtassets\\b'),
]]
def issuer(name):
    for l, p in ISS:
        if name and p.search(name): return l
    return "Altro / non riconosciuto"
